/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables.records;


import edu.java.domain.jooq.tables.Link;

import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LinkRecord extends UpdatableRecordImpl<LinkRecord> implements Record6<Long, String, String, OffsetDateTime, OffsetDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.link.id</code>.
     */
    public void setId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.link.id</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.link.url</code>.
     */
    public void setUrl(@Nullable String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.link.url</code>.
     */
    @Nullable
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.link.description</code>.
     */
    public void setDescription(@NotNull String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.link.description</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.link.updated_at</code>.
     */
    public void setUpdatedAt(@Nullable OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.link.updated_at</code>.
     */
    @Nullable
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.link.last_checked_at</code>.
     */
    public void setLastCheckedAt(@Nullable OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.link.last_checked_at</code>.
     */
    @Nullable
    public OffsetDateTime getLastCheckedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.link.meta_information</code>.
     */
    public void setMetaInformation(@Nullable String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.link.meta_information</code>.
     */
    @Nullable
    public String getMetaInformation() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row6<Long, String, String, OffsetDateTime, OffsetDateTime, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row6<Long, String, String, OffsetDateTime, OffsetDateTime, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Link.LINK.ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return Link.LINK.URL;
    }

    @Override
    @NotNull
    public Field<String> field3() {
        return Link.LINK.DESCRIPTION;
    }

    @Override
    @NotNull
    public Field<OffsetDateTime> field4() {
        return Link.LINK.UPDATED_AT;
    }

    @Override
    @NotNull
    public Field<OffsetDateTime> field5() {
        return Link.LINK.LAST_CHECKED_AT;
    }

    @Override
    @NotNull
    public Field<String> field6() {
        return Link.LINK.META_INFORMATION;
    }

    @Override
    @Nullable
    public Long component1() {
        return getId();
    }

    @Override
    @Nullable
    public String component2() {
        return getUrl();
    }

    @Override
    @NotNull
    public String component3() {
        return getDescription();
    }

    @Override
    @Nullable
    public OffsetDateTime component4() {
        return getUpdatedAt();
    }

    @Override
    @Nullable
    public OffsetDateTime component5() {
        return getLastCheckedAt();
    }

    @Override
    @Nullable
    public String component6() {
        return getMetaInformation();
    }

    @Override
    @Nullable
    public Long value1() {
        return getId();
    }

    @Override
    @Nullable
    public String value2() {
        return getUrl();
    }

    @Override
    @NotNull
    public String value3() {
        return getDescription();
    }

    @Override
    @Nullable
    public OffsetDateTime value4() {
        return getUpdatedAt();
    }

    @Override
    @Nullable
    public OffsetDateTime value5() {
        return getLastCheckedAt();
    }

    @Override
    @Nullable
    public String value6() {
        return getMetaInformation();
    }

    @Override
    @NotNull
    public LinkRecord value1(@Nullable Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value2(@Nullable String value) {
        setUrl(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value3(@NotNull String value) {
        setDescription(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value4(@Nullable OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value5(@Nullable OffsetDateTime value) {
        setLastCheckedAt(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value6(@Nullable String value) {
        setMetaInformation(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord values(@Nullable Long value1, @Nullable String value2, @NotNull String value3, @Nullable OffsetDateTime value4, @Nullable OffsetDateTime value5, @Nullable String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkRecord
     */
    public LinkRecord() {
        super(Link.LINK);
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    @ConstructorProperties({ "id", "url", "description", "updatedAt", "lastCheckedAt", "metaInformation" })
    public LinkRecord(@Nullable Long id, @Nullable String url, @NotNull String description, @Nullable OffsetDateTime updatedAt, @Nullable OffsetDateTime lastCheckedAt, @Nullable String metaInformation) {
        super(Link.LINK);

        setId(id);
        setUrl(url);
        setDescription(description);
        setUpdatedAt(updatedAt);
        setLastCheckedAt(lastCheckedAt);
        setMetaInformation(metaInformation);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    public LinkRecord(edu.java.domain.jooq.tables.pojos.Link value) {
        super(Link.LINK);

        if (value != null) {
            setId(value.getId());
            setUrl(value.getUrl());
            setDescription(value.getDescription());
            setUpdatedAt(value.getUpdatedAt());
            setLastCheckedAt(value.getLastCheckedAt());
            setMetaInformation(value.getMetaInformation());
            resetChangedOnNotNull();
        }
    }
}
