app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
    max-links-per-check: 100
  github-token: ${GITHUB_TOKEN}
  stackoverflow:
    key: ${STACKOVERFLOW_KEY}
    access-token: ${STACKOVERFLOW_ACCESS_TOKEN}
  database-access-type: jpa

provider:
  github:
    url: https://api.github.com
  stackoverflow:
    url: https://api.stackexchange.com/2.3

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

bot:
  url: http://localhost:8090

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

retry:
  type: linear
  max-attempts: 5
  min-delay: 5s
  codes: 404, 500, 502
  max-delay: 50s
