/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Link implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String url;
    private String description;
    private OffsetDateTime updatedAt;
    private OffsetDateTime lastCheckedAt;
    private String metaInformation;

    public Link() {}

    public Link(Link value) {
        this.id = value.id;
        this.url = value.url;
        this.description = value.description;
        this.updatedAt = value.updatedAt;
        this.lastCheckedAt = value.lastCheckedAt;
        this.metaInformation = value.metaInformation;
    }

    @ConstructorProperties({ "id", "url", "description", "updatedAt", "lastCheckedAt", "metaInformation" })
    public Link(
        @Nullable Long id,
        @Nullable String url,
        @NotNull String description,
        @Nullable OffsetDateTime updatedAt,
        @Nullable OffsetDateTime lastCheckedAt,
        @Nullable String metaInformation
    ) {
        this.id = id;
        this.url = url;
        this.description = description;
        this.updatedAt = updatedAt;
        this.lastCheckedAt = lastCheckedAt;
        this.metaInformation = metaInformation;
    }

    /**
     * Getter for <code>public.link.id</code>.
     */
    @Nullable
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.link.id</code>.
     */
    public void setId(@Nullable Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.link.url</code>.
     */
    @Nullable
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>public.link.url</code>.
     */
    public void setUrl(@Nullable String url) {
        this.url = url;
    }

    /**
     * Getter for <code>public.link.description</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.link.description</code>.
     */
    public void setDescription(@NotNull String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.link.updated_at</code>.
     */
    @Nullable
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.link.updated_at</code>.
     */
    public void setUpdatedAt(@Nullable OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.link.last_checked_at</code>.
     */
    @Nullable
    public OffsetDateTime getLastCheckedAt() {
        return this.lastCheckedAt;
    }

    /**
     * Setter for <code>public.link.last_checked_at</code>.
     */
    public void setLastCheckedAt(@Nullable OffsetDateTime lastCheckedAt) {
        this.lastCheckedAt = lastCheckedAt;
    }

    /**
     * Getter for <code>public.link.meta_information</code>.
     */
    @Nullable
    public String getMetaInformation() {
        return this.metaInformation;
    }

    /**
     * Setter for <code>public.link.meta_information</code>.
     */
    public void setMetaInformation(@Nullable String metaInformation) {
        this.metaInformation = metaInformation;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Link other = (Link) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.url == null) {
            if (other.url != null)
                return false;
        }
        else if (!this.url.equals(other.url))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        if (this.lastCheckedAt == null) {
            if (other.lastCheckedAt != null)
                return false;
        }
        else if (!this.lastCheckedAt.equals(other.lastCheckedAt))
            return false;
        if (this.metaInformation == null) {
            if (other.metaInformation != null)
                return false;
        }
        else if (!this.metaInformation.equals(other.metaInformation))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.url == null) ? 0 : this.url.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        result = prime * result + ((this.lastCheckedAt == null) ? 0 : this.lastCheckedAt.hashCode());
        result = prime * result + ((this.metaInformation == null) ? 0 : this.metaInformation.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Link (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(description);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(lastCheckedAt);
        sb.append(", ").append(metaInformation);

        sb.append(")");
        return sb.toString();
    }
}
