/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq;


import edu.java.domain.jooq.tables.ChatLink;
import edu.java.domain.jooq.tables.Link;
import edu.java.domain.jooq.tables.TgChat;
import edu.java.domain.jooq.tables.records.ChatLinkRecord;
import edu.java.domain.jooq.tables.records.LinkRecord;
import edu.java.domain.jooq.tables.records.TgChatRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatLinkRecord> CHAT_LINK_PKEY = Internal.createUniqueKey(ChatLink.CHAT_LINK, DSL.name("chat_link_pkey"), new TableField[] { ChatLink.CHAT_LINK.CHAT_ID, ChatLink.CHAT_LINK.LINK_ID }, true);
    public static final UniqueKey<LinkRecord> LINK_PKEY = Internal.createUniqueKey(Link.LINK, DSL.name("link_pkey"), new TableField[] { Link.LINK.ID }, true);
    public static final UniqueKey<LinkRecord> LINK_URL_KEY = Internal.createUniqueKey(Link.LINK, DSL.name("link_url_key"), new TableField[] { Link.LINK.URL }, true);
    public static final UniqueKey<TgChatRecord> TG_CHAT_PKEY = Internal.createUniqueKey(TgChat.TG_CHAT, DSL.name("tg_chat_pkey"), new TableField[] { TgChat.TG_CHAT.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ChatLinkRecord, TgChatRecord> CHAT_LINK__CHAT_LINK_CHAT_ID_FKEY = Internal.createForeignKey(ChatLink.CHAT_LINK, DSL.name("chat_link_chat_id_fkey"), new TableField[] { ChatLink.CHAT_LINK.CHAT_ID }, Keys.TG_CHAT_PKEY, new TableField[] { TgChat.TG_CHAT.ID }, true);
    public static final ForeignKey<ChatLinkRecord, LinkRecord> CHAT_LINK__CHAT_LINK_LINK_ID_FKEY = Internal.createForeignKey(ChatLink.CHAT_LINK, DSL.name("chat_link_link_id_fkey"), new TableField[] { ChatLink.CHAT_LINK.LINK_ID }, Keys.LINK_PKEY, new TableField[] { Link.LINK.ID }, true);
}
